#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/ayn/qcs8550-common

PRODUCT_COPY_FILES += \
    vendor/ayn/qcs8550-common/proprietary/system/etc/sysconfig/qti_whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/qti_whitelist.xml \
    vendor/ayn/qcs8550-common/proprietary/system_ext/etc/init/qspmsvc.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/qspmsvc.rc \
    vendor/ayn/qcs8550-common/proprietary/system_ext/etc/init/wfdservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/wfdservice.rc \
    vendor/ayn/qcs8550-common/proprietary/system_ext/etc/permissions/wfd-system-ext-privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/wfd-system-ext-privapp-permissions-qti.xml \
    vendor/ayn/qcs8550-common/proprietary/system_ext/etc/seccomp_policy/wfdservice64.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/wfdservice64.policy \
    vendor/ayn/qcs8550-common/proprietary/system_ext/etc/wfdconfigsink.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/wfdconfigsink.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/ffv_models/ffv__5.0.1_0.1__3.0.0_0.0__eai_2.10_enpu3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__5.0.1_0.1__3.0.0_0.0__eai_2.10_enpu3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/ffv_models/ffv__5.0.1_0.1__eai_2.10_enpu3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__5.0.1_0.1__eai_2.10_enpu3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/ffv_models/ffv__5.0.2_0.1__eai_2.10_enpu.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__5.0.2_0.1__eai_2.10_enpu.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/kalama_qrd/QRD_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kalama_qrd/QRD_acdb_cal.acdb \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/kalama_qrd/QRD_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kalama_qrd/QRD_workspaceFileXml.qwsp \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.7_enpu3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.7_enpu3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.2_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.2_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.3_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.3_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/charger_fw_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fw_fstab.qti \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/configstore/vpp.configstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/configstore/vpp.configstore.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/DPU660.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU660.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/DPU670.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU670.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/DPU720.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU720.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/DPU7__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU7__.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/DPU820.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU820.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/DPU8__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU8__.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/DPU960.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU960.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/eva/facedetection/model3.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facedetection/model3.dat \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-qti.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.wfdhdcp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.wfdhdcp.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-spu-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-spu-qti.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-strongbox-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-strongbox-service-qti.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-qti.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/hw/init.qti.kernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.qti.kernel.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/init.qti.media.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.media.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/init.spdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.spdaemon.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/init.spuservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.spuservice.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/init.vendor.qti.spu@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.qti.spu@1.1-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/init_thermal-engine-v2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine-v2.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/poweropt-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/poweropt-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/qconfig.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qconfig.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/qesdk-manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qesdk-manager.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/qmipriod.debug.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.debug.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/qmipriod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/qwesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qwesd.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.diag.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.factory@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.factory@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.iop@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.iop@2.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.limits-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.limits-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.perf-hal-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf-hal-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.hardware.servicetracker@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.servicetracker@1.2-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.media.c2audio@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2audio@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.qspmhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.qspmhal@1.0-service.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/vppservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vppservice.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/init/wfdvndservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wfdvndservice.rc \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/AdaptLaunchFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/AdaptLaunchFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/AppClassifierFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/AppClassifierFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/LightningLaunchesFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/LightningLaunchesFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/PreKillFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/PreKillFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/PrefAppsFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/PrefAppsFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/ProCompFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/ProCompFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/QAPE.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/QAPE.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/QGPE.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/QGPE.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/QGPEActionMap.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/QGPEActionMap.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/SilkyScrollsFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/SilkyScrollsFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/prekill/prekill_2GB.data:$(TARGET_COPY_OUT_VENDOR)/etc/lm/prekill/prekill_2GB.data \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/prekill/prekill_4GB.data:$(TARGET_COPY_OUT_VENDOR)/etc/lm/prekill/prekill_4GB.data \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/prekill/prekill_6GB.data:$(TARGET_COPY_OUT_VENDOR)/etc/lm/prekill/prekill_6GB.data \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/lm/sPLHFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/sPLHFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/media_kalama_iot/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_kalama_iot/video_system_specs.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/media_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/media_profiles_kalama_iot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_kalama_iot.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/models/acd/event.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/event.eai \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/models/acd/music.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/music.eai \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/models/acd/speech.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/speech.eai \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/avcsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/avcsysnodesconfigs.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/commonsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonsysnodesconfigs.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/targetavcsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetavcsysnodesconfigs.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/targetsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetsysnodesconfigs.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/testcommonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/testcommonresourceconfigs.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/perf/testtargetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/testtargetresourceconfigs.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/permissions/android.hardware.light.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.light.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/permissions/android.hardware.strongbox_keystore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.strongbox_keystore.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/permissions/vendor.qti.hardware.factory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.qti.hardware.factory.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/pwr/AODPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/AODPowerOptFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/pwr/PSMPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/PSMPowerOptFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/pwr/PowerFeatureConfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/PowerFeatureConfig.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/pwr/StandbyFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/StandbyFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/pwr/VideoPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/VideoPowerOptFeature.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base-arm64.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext-arm64.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/qesdk.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qesdk.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/qspm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qspm.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/qwesd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qwesd@2.0.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/wfdhdcphalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdhdcphalservice.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/wfdvndservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdvndservice.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/seccomp_policy/wifidisplayhalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wifidisplayhalservice.policy \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/json.lst:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/json.lst \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_ak991x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_bu52053nvx_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_default_sensors.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_dynamic_sensors.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_dynamic_sensors_template.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_dynamic_sensors_template.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_fcal_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_fcal_ak991x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_hdk_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_hdk_ak991x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_hdk_lsm6dsv_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_hdk_lsm6dsv_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_hdk_lsm6dsv_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_hdk_lsm6dsv_1.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_hhg_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_hhg_ak991x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_hhg_lsm6dsv_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_hhg_lsm6dsv_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_icm4x6xx_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_ak991x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_amd_sw_disabled.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_amd_sw_enabled.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_ak991x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_bu52053nvx_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_dae.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_lps22df_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_lps22df_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_lsm6dsv_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_lsm6dsv_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_lsm6dsv_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_lsm6dsv_1.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_power_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_sht4x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_sht4x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_sx932x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_hdk_tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_hdk_tmd2755_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_icm4x6xx_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_icp101xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_icp101xx_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_navmez_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_navmez_icm4x6xx_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_navmez_rev2_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_navmez_rev2_icm4x6xx_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_rb5p_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_rb5p_power_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_iot_tdkmez_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_iot_tdkmez_icm4x6xx_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_irq.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_lps22df_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_lps22df_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_lsm6dsv_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_lsm6dsv_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_lsm6dsv_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_lsm6dsv_1.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_ltr568_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_ltr568_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_mmc36xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_mmc36xx_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_mtp_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_mtp_ak991x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_mtp_lsm6dsv_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_mtp_lsm6dsv_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_mtp_lsm6dsv_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_mtp_lsm6dsv_1.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_power_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_qmc6308_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_qmc6308_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_qrd_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_qrd_ak991x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_qrd_lsm6dsv_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_qrd_lsm6dsv_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_qrd_tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_qrd_tmd2755_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_qsh_ble_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_qsh_ble_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_sht4x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_sht4x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_stk3x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_stk3x3x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_sx932x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_tmd2755_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_vertigo_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_vertigo_ak991x_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_vertigo_lsm6dsv_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_vertigo_lsm6dsv_0.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/kailua_vertigo_lsm6dsv_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_vertigo_lsm6dsv_1.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/qsh_ble.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_ble.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/qsh_camera.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_amd.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_ttw.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_ttw.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_ccd_v2_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_0_walk.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_ccd_v3_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_0_walk.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_sensors.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_ccd_v5.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_offbody_detect_phone.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_offbody_detect_phone.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_transport_ppe.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_transport_ppe.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/wfdconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wfdconfig.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/wifi/icm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/icm.conf \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/wifi/kiwi_v2/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/kiwi_v2/WCNSS_qcom_cfg.ini \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/wifi/vendor_cmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/vendor_cmd.xml \
    vendor/ayn/qcs8550-common/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/a740_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_sqe.fw \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/a740_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.b00 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/a740_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.b01 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/a740_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.b02 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/a740_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.elf \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/a740_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/a740_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.mdt \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b00 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/gen70e00_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70e00_sqe.fw \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/gen70e00_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70e00_zap.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/gmu_gen70200.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70200.bin \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/gmu_gen70e00.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70e00.bin \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/kiwi/amss20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/amss20.bin \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/vpu20_1v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_1v.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/vpu20_1v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_1v_unsigned.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/vpu20_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/vpu20_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v_unsigned.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/vpu30_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_4v.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/vpu30_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_4v_unsigned.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v_unsigned.mbn \
    vendor/ayn/qcs8550-common/proprietary/vendor/gpu/kbc/sequence_manifest.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/sequence_manifest.bin \
    vendor/ayn/qcs8550-common/proprietary/vendor/gpu/kbc/unified_kbcs_32.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_32.bin \
    vendor/ayn/qcs8550-common/proprietary/vendor/gpu/kbc/unified_kbcs_64.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_64.bin \
    vendor/ayn/qcs8550-common/proprietary/vendor/gpu/kbc/unified_ksqs.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_ksqs.bin

PRODUCT_PACKAGES += \
    btaudio_offload_if \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libVkLayer_ADRENO_qprofiler \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth.audio-impl-qti \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.bluetooth@1.1-impl-qti \
    android.hardware.gatekeeper@1.0-impl-qti \
    audio.primary.kalama \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.bttpi-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    vendor.qti.hardware.servicetracker@1.2-impl \
    vulkan.adreno \
    libAlacSwDec \
    libApeSwDec \
    libCB \
    libCOSNet_spatial_qnn_quantized \
    libEvrcSwCodec \
    libFileMux_proprietary \
    libFlacSwDec \
    libGPMTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libOpenCL \
    libPeripheralStateUtils \
    libQSEEComAPI \
    libQTEEConnector_vendor \
    libQcelp13SwCodec \
    libQnnCpu \
    libQnnHtp \
    libQnnHtpPrepare \
    libQnnHtpV73Stub \
    libQnnSystem \
    libTrustedUI \
    libTrustedUITZ \
    libTrustedUIVM \
    libadaptlaunch \
    libadm \
    libadreno_app_profiles \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libagm \
    libaodoptfeature \
    libapengine \
    libappclassifier \
    libar-pal \
    libaudio_log_utils \
    libbacklight-calib \
    libbluetooth_audio_session_aidl_qti \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libbt-hidlclient \
    libbtnv \
    libcapiv2svacnnvendor \
    libcapiv2svarnnvendor \
    libcapiv2udk7vendor \
    libcapiv2uvvendor \
    libcdsp_default_listener \
    libcdsprpc \
    libclstc_algorithm_adapter \
    libclstc_gcp_adapter \
    libclstc_tm \
    libconfigdb \
    libcpion \
    libcv_common \
    libdiag \
    libdigital-dimming \
    libdisp-aba \
    libdisplayqos \
    libdisplayskuutils \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdsd2pcm \
    libdsi_netctrl \
    libdsutils \
    libeai_fixed \
    libeai_float \
    libeva \
    libeva_util \
    libfastcvdsp_stub \
    libfastcvopt \
    libfeutils \
    libgame_enhance \
    libgpt \
    libgpudataproducer \
    libgsl \
    libhdcpsrm \
    libhdr_backlight_adapter \
    libhdr_tm \
    libidl \
    libintervmipc \
    libkcl \
    libkernelmanager \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblearningmodule \
    liblightninglaunches \
    liblistensoundmodel2vendor \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    liblmthermallistner \
    liblmutils-ns \
    libloadalgo_stub \
    libmcs \
    libmdmdetect \
    libmdsprpc \
    libmemperfd \
    libmemutils \
    libmeters-ns \
    libmeters \
    libminkdescriptor \
    libminksocket_vendor \
    libmm-hdcpmgr \
    libmmosal_vendor \
    libmmrtpdecoder_vendor \
    libmmrtpencoder_vendor \
    libnanopb \
    libnetmgr \
    libnetmgrxfrmutils \
    liboemcrypto \
    libops \
    libpasrutils \
    libpdmapper \
    libpdnotifier \
    libperfconfig \
    libperfgluelayer \
    libperfioctl \
    libperipheral_client \
    libpowercore \
    libprefapps \
    libprekill \
    libprocomp \
    libpsmoptfeature \
    libqapesdk \
    libqc2audio_base \
    libqc2audio_basecodec \
    libqc2audio_core \
    libqc2audio_hooks \
    libqc2audio_hwaudiocodec \
    libqc2audio_platform \
    libqc2audio_swaudiocodec \
    libqc2audio_utils \
    libqc2colorconvertfilter \
    libqc2filter \
    libqc2vppfilter \
    libqcbor \
    libqcc_sdk \
    libqcci_legacy \
    libqcodec2_base \
    libqcodec2_basecodec \
    libqcodec2_core \
    libqcodec2_cvpfilter \
    libqcodec2_filterbase \
    libqcodec2_hooks \
    libqcodec2_imgtxrfilter \
    libqcodec2_mockfilter \
    libqcodec2_mockqc2filter \
    libqcodec2_platform \
    libqcodec2_salmapfilter \
    libqcodec2_streaminteg_filter \
    libqcodec2_utils \
    libqcodec2_v4l2codec \
    libqconfigclient \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdi \
    libqesdk2_0 \
    libqesdk_manager \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_csvt_srvc \
    libqmi_encdec \
    libqmi_legacy \
    libqmiextservices \
    libqmiservices \
    libqnnengine \
    libqrtr \
    libqrtrclient \
    libqseed3 \
    libqsocket \
    libqti-iopd-client \
    libqti-iopd \
    libqti-perfd-client \
    libqti-perfd \
    libqti-qesdk-secure \
    libqti-util \
    libqti-utils \
    libqtigefar \
    libqtikeymaster4 \
    libqtikeymint \
    librcmask \
    librpmb \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsensorcal \
    libsensorslog \
    libsi \
    libsilkyscrolls \
    libskewknob \
    libsmemlog \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libsns_api \
    libsns_device_mode_stub \
    libsns_direct_channel_stub \
    libsns_dynamic_loader_stub \
    libsns_registry_skel \
    libsns_remote_proc_state_stub \
    libsnsapi \
    libsnsdiaglog \
    libsnsutils \
    libsoc_helper \
    libspcom \
    libspl \
    libsplh \
    libspukeymint \
    libspukeymintdeviceutils \
    libspukeymintprovision \
    libspukeymintutils \
    libssc \
    libssc_default_listener \
    libssd \
    libstandbyfeature \
    libstreamparser \
    libsubsystem_control \
    libsysmon_cdsp_skel \
    libsystem_health_mon \
    libtestutils \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libtrustedapploader \
    libvideooptfeature \
    libvideotxr \
    libvideoutils \
    libvmfilexfer \
    libvppclient \
    libvppcommon \
    libvpphcp \
    libvpphvx \
    libvppimmotion \
    libvpplibrary \
    libvpptestutils \
    libvui_dmgr \
    libvui_dmgr_client \
    libwfdcodecv4l2_proprietary \
    libwfdcommonutils_proprietary \
    libwfdconfigutils_proprietary \
    libwfddisplayconfig_vendor \
    libwfdhdcpcp \
    libwfdmminterface_proprietary \
    libwfdmmservice_proprietary \
    libwfdmmsrc_proprietary \
    libwfdmodulehdcpsession \
    libwfdrtsp_vendor \
    libwfdsessionmodule \
    libwfdsourcesession_proprietary \
    libwfdsourcesm_proprietary \
    libwfduibcinterface_vendor \
    libwfduibcsink_vendor \
    libwfduibcsinkinterface_vendor \
    libwfduibcsrc_vendor \
    libwfduibcsrcinterface_vendor \
    libwfdutils_proprietary \
    libwvaidl \
    libxml \
    qti.video.utils.videobufferlayout \
    sensors.ssc \
    libasphere \
    libquasar \
    libshoebox \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.color@1.6 \
    vendor.display.color@1.7 \
    vendor.display.postproc@1.0 \
    vendor.qti.diaghal@1.0_vendor \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.bttpi-V2-ndk \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.factory@1.0 \
    vendor.qti.hardware.factory@1.1 \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.limits@1.0 \
    vendor.qti.hardware.limits@1.1 \
    vendor.qti.hardware.limits@1.2 \
    vendor.qti.hardware.pal@1.0-impl \
    vendor.qti.hardware.power.powermodule@1.0 \
    vendor.qti.hardware.qccsyshal@1.0_vendor \
    vendor.qti.hardware.qccsyshal@1.1_vendor \
    vendor.qti.hardware.qccsyshal@1.2_vendor \
    vendor.qti.hardware.qconfig@1.0 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    vendor.qti.hardware.trustedui@1.0 \
    vendor.qti.hardware.trustedui@1.1 \
    vendor.qti.hardware.trustedui@1.2 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.hardware.vpp@1.3 \
    vendor.qti.hardware.vpp@2.0 \
    vendor.qti.hardware.wifidisplaysession@1.0_vendor \
    vendor.qti.hardware.wifidisplaysessionl@1.0-halimpl \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.memory.pasrmanager@1.1 \
    vendor.qti.qesdhal@1.0 \
    vendor.qti.qesdhal@1.1 \
    vendor.qti.qesdhal@1.2 \
    vendor.qti.qesdhal@1.3 \
    vendor.qti.qesdhal@1.4-impl \
    vendor.qti.qesdhal@1.4 \
    vendor.qti.qesdsys-V3-ndk \
    vendor.qti.qspmhal@1.0-impl \
    vendor.qti.qspmhal@1.0_vendor \
    vendor.qti.spu@1.0 \
    vendor.qti.spu@1.1 \
    vendor.qti.spu@2.0 \
    vendor_lib_rfsa_adsp_bm3a68v08s11n29_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n30_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n35_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n36_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n37_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n38_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n39_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n40_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n46_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n47_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n48_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n49_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n52_bin \
    vendor_lib_rfsa_adsp_bm3a68v08s11n53_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n02_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n03_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n04_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n06_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n07_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n08_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n09_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n12_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n13_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n14_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n15_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n16_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n17_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n18_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n19_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n20_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n21_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n22_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n23_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n24_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n25_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n26_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n27_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n28_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n41_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n42_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n43_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n44_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n45_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n50_bin \
    vendor_lib_rfsa_adsp_bm3a73v08s11n51_bin \
    vendor_lib_rfsa_adsp_libDspIOProxy_skel_so \
    vendor_lib_rfsa_adsp_libQ6MSFR_manager_skel_so \
    vendor_lib_rfsa_adsp_libQnnHtpV73Skel_so \
    vendor_lib_rfsa_adsp_libVppAisQnnHtp_so \
    vendor_lib_rfsa_adsp_libVppFrcQnnHtp_so \
    vendor_lib_rfsa_adsp_libadsp_jpege_skel_so \
    vendor_lib_rfsa_adsp_libapn_dsp_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_v2_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_qvrcam_receiver_so \
    vendor_lib_rfsa_adsp_libevadsp_3_0_so \
    vendor_lib_rfsa_adsp_libeye_tracking_dsp_sample_skel_so \
    vendor_lib_rfsa_adsp_libhalide_hexagon_remote_skel_so \
    vendor_lib_rfsa_adsp_libhdr_skel_so \
    vendor_lib_rfsa_adsp_libhme_dsp_skel_so \
    vendor_lib_rfsa_adsp_libmctfengine_skel_so \
    vendor_lib_rfsa_adsp_libmobilenet_dsp_frc_so \
    vendor_lib_rfsa_adsp_libmobilenet_dsp_frc_networks_so \
    vendor_lib_rfsa_adsp_libqvr_3dof_tracker_skel_so \
    vendor_lib_rfsa_adsp_libqvr_cam_dsp_driver_skel_so \
    vendor_lib_rfsa_adsp_libqvr_dsp_driver_skel_so \
    vendor_lib_rfsa_adsp_libtracker_6dof_skel_8450_so \
    vendor_lib_rfsa_adsp_libvpp_ais_so \
    vendor_lib_rfsa_adsp_libvpp_ais_networks_so \
    vendor_lib_rfsa_adsp_libvpp_frc_so \
    vendor_lib_rfsa_adsp_libvpp_svc_skel_so \
    vendor_lib_rfsa_adsp_libvpp_vqa_networks_so \
    vendor_lib_rfsa_adsp_libvpt_action_recognition_so \
    com.qualcomm.qti.ant@1.0 \
    libmmosal \
    libmmparser_lite \
    libmmrtpdecoder \
    libmmrtpencoder \
    libqspmsvc \
    libwfdavenhancements \
    libwfdclient \
    libwfdcommonutils \
    libwfdconfigutils \
    libwfddisplayconfig \
    libwfdmminterface \
    libwfdmmsink \
    libwfdmmsrc_system \
    libwfdnative \
    libwfdrtsp \
    libwfdservice \
    libwfdsinksm \
    libwfduibcinterface \
    libwfduibcsink \
    libwfduibcsinkinterface \
    libwfduibcsrc \
    libwfduibcsrcinterface \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccsyshal@1.1 \
    vendor.qti.hardware.qccsyshal@1.2 \
    vendor.qti.hardware.wifidisplaysession@1.0 \
    vendor.qti.hardware.wifidisplaysession_aidl-V1-ndk \
    vendor.qti.qspmhal@1.0 \
    TimeService \
    WfdService \
    WfdCommon \
    android.hardware.keymaster@4.0-service-strongbox-qti.xml \
    android.hardware.security.keymint-service-qti.xml \
    bttpi-saidl.xml \
    c2_manifest_vendor.xml \
    c2_manifest_vendor_audio.xml \
    manifest_android.hardware.drm-service.widevine.xml \
    vendor.qti.hardware.limits-service.xml \
    vendor.qti.hardware.perf.xml \
    vendor.qti.hardware.power.powermodule.xml \
    vendor.qti.hardware.qconfig@1.0-service.xml \
    vendor.qti.hardware.servicetracker@1.2-service.xml \
    vendor.qti.hardware.vpp@2.0-service.xml \
    vendor.qti.hardware.wifidisplaysession-service.xml \
    adsprpcd \
    cdsprpcd \
    cnss-daemon \
    diag-router \
    dspservice \
    android.hardware.bluetooth@1.1-service-qti \
    android.hardware.drm-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.gatekeeper@1.0-service-spu-qti \
    android.hardware.keymaster@4.0-service-qti \
    android.hardware.keymaster@4.0-strongbox-service-qti \
    android.hardware.security.keymint-service-qti \
    android.hardware.security.keymint-service-spu-qti \
    qconfigservice \
    vendor.display.color@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.factory@1.0-service \
    vendor.qti.hardware.iop@2.0-service \
    vendor.qti.hardware.limits@1.2-service \
    vendor.qti.hardware.perf-hal-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    vendor.qti.hardware.servicetracker@1.2-service \
    vendor.qti.media.c2@1.0-service \
    vendor.qti.media.c2audio@1.0-service \
    vendor.qti.spu@1.1-service \
    vendor.qti.spu@2.0-service \
    init.kernel.post_boot-kalama \
    init.kernel.post_boot-kalama_3_2_1 \
    init.kernel.post_boot-kalama_3_4_0 \
    init.kernel.post_boot-kalama_default_3_4_1 \
    init.kernel.post_boot \
    init.qcom.class_core \
    init.qcom.post_boot \
    init.qcom.sensors \
    init.qti.kernel \
    init.qti.keymaster \
    init.qti.media \
    init.qti.qcv \
    init.qti.write \
    irsc_util \
    loadalgo \
    mmid \
    msm_irqbalance \
    pd-mapper \
    pm-proxy \
    pm-service \
    poweropt-service \
    ppd \
    qdcmss \
    qesdk-manager \
    qmipriod \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qwesd \
    sec_nvm \
    sensors.qti \
    spdaemon \
    sscrpcd \
    ssgtzd \
    system_dlkm_modprobe \
    tftp_server \
    thermal-engine-v2 \
    time_daemon \
    vendor.qti.qspmhal@1.0-service \
    vendor_modprobe \
    vppservice \
    wifidisplayhalservice \
    qspmsvc \
    wfdservice64

PRODUCT_PACKAGES += \
    system_ext_priv-app_WfdService_lib_arm64_libwfdnative_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so

PRODUCT_BOOT_JARS += \
    WfdCommon
